language: android
os: linux
jdk: oraclejdk8
dist: trusty

android:
  components:
    - build-tools-29.0.2
    - android-29

script:
  - chmod +x ./gradlew
  - ./gradlew build --scan -s

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
